-- MySQL Script generated by MySQL Workbench
-- Tue Dec 29 16:50:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
/*SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cfb2fjadl5i6mh6w
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cfb2fjadl5i6mh6w` ;

-- -----------------------------------------------------
-- Schema cfb2fjadl5i6mh6w
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cfb2fjadl5i6mh6w` DEFAULT CHARACTER SET utf8 ;
USE `cfb2fjadl5i6mh6w` ;*/

-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`BaiHoc`
-- -----------------------------------------------------
USE cfb2fjadl5i6mh6w;
-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`LinhVucCap2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`LinhVucCap2` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`LinhVucCap2` (
 `idLinhVucCap2` INT NOT NULL AUTO_INCREMENT,
 `MaLinhVuc` CHAR(20) NULL,
 `TenLinhVuc` VARCHAR(256) NULL,
 `LinhVucCap1_idLinhVuc` INT NOT NULL, PRIMARY KEY (`idLinhVucCap2`), 
 INDEX `fk_LinhVucCap2_LinhVucCap11_idx` (`LinhVucCap1_idLinhVuc` ASC) VISIBLE, 
 CONSTRAINT `fk_LinhVucCap2_LinhVucCap11` FOREIGN KEY (`LinhVucCap1_idLinhVuc`) 
 REFERENCES `cfb2fjadl5i6mh6w`.`LinhVucCap1` (`idLinhVuc`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`LinhVucCap1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`LinhVucCap1` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`LinhVucCap1` (
 `idLinhVuc` INT NOT NULL AUTO_INCREMENT,
 `MaLinhVuc` CHAR(20) NULL,
 `TenLinhVuc` VARCHAR(256) NULL, PRIMARY KEY (`idLinhVuc`)) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`GiangVien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`GiangVien` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`GiangVien` (
 `idGiangVien` INT NOT NULL AUTO_INCREMENT,
 `TenGiangVien` VARCHAR(256) NULL,
 `NgaySinh` DATETIME NULL,
 `MoTa` VARCHAR(2048) NULL,
 `HinhDaiDien` VARCHAR(2048) NULL,
 `Email` VARCHAR(256) NULL,
 `TaiKhoan_idTaiKhoan` INT NOT NULL, PRIMARY KEY (`idGiangVien`), 
 INDEX `fk_GiangVien_TaiKhoan1_idx` (`TaiKhoan_idTaiKhoan` ASC) VISIBLE, 
 UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE, 
 CONSTRAINT `fk_GiangVien_TaiKhoan` FOREIGN KEY (`TaiKhoan_idTaiKhoan`) REFERENCES `cfb2fjadl5i6mh6w`.`TaiKhoan` (`idTaiKhoan`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`KhoaHoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`KhoaHoc` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`KhoaHoc` (
 `IdKhoaHoc` INT NOT NULL AUTO_INCREMENT,
 `MaKhoaHoc` CHAR(20) NULL,
 `TenKhoaHoc` VARCHAR(256) NULL,
 `MoTaNgan` VARCHAR(2048) NULL,
 `MoTaChiTiet` VARCHAR(4096) NULL,
 `DiemDanhGia` FLOAT NULL,
 `SoLuongHVDanhGia` INT NULL,
 `SoLuongHVDangKy` INT NULL,
 `NgayCapNhat` DATETIME NULL,
 `SoLuotXem` INT NULL,
 `HocPhi` FLOAT NULL,
 `KhuyenMai` FLOAT NULL,
 `HinhDaiDien` VARCHAR(2048) NULL,
 `TrangThai` TINYINT NULL,
 `NguoiTao` INT NOT NULL,
 `NguoiDay` INT NOT NULL,
 `LinhVuc` INT NOT NULL,
 `HienThi` INT NOT NULL, PRIMARY KEY (`IdKhoaHoc`), INDEX `fk_KhoaHoc_GiangVien1_idx` (`NguoiTao` ASC) VISIBLE, INDEX `fk_KhoaHoc_GiangVien1_idx1` (`NguoiDay` ASC) VISIBLE, INDEX `fk_KhoaHoc_LinhVucCap21_idx` (`LinhVuc` ASC) VISIBLE, CONSTRAINT `fk_KhoaHoc_GiangVien` FOREIGN KEY (`NguoiTao`) REFERENCES `cfb2fjadl5i6mh6w`.`GiangVien` (`idGiangVien`) ON
DELETE CASCADE ON
UPDATE NO ACTION, CONSTRAINT `fk_KhoaHoc_GiangVien1` FOREIGN KEY (`NguoiDay`) REFERENCES `cfb2fjadl5i6mh6w`.`GiangVien` (`idGiangVien`) ON
DELETE CASCADE ON
UPDATE NO ACTION, CONSTRAINT `fk_KhoaHoc_LinhVucCap21` FOREIGN KEY (`LinhVuc`) REFERENCES `cfb2fjadl5i6mh6w`.`LinhVucCap2` (`idLinhVucCap2`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`ChuongKhoaHoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`ChuongKhoaHoc` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`ChuongKhoaHoc` (
 `idChuongKhoaHoc` INT NOT NULL AUTO_INCREMENT,
 `TenChuong` VARCHAR(100) NULL,
 `KhoaHoc_IdKhoaHoc` INT NOT NULL, PRIMARY KEY (`idChuongKhoaHoc`), 
 INDEX `fk_ChuongKhoaHoc_KhoaHoc1_idx` (`KhoaHoc_IdKhoaHoc` ASC) VISIBLE, 
 CONSTRAINT `fk_ChuongKhoaHoc_KhoaHoc1` FOREIGN KEY (`KhoaHoc_IdKhoaHoc`) REFERENCES `cfb2fjadl5i6mh6w`.`KhoaHoc` (`IdKhoaHoc`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;

DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`BaiHoc` ;

CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`BaiHoc` (
 `idBaiHoc` INT NOT NULL AUTO_INCREMENT,
 `TenBaiHoc` VARCHAR(256) NULL,
 `Mieu ta` VARCHAR(1028) NULL,
 `ChuongKhoaHoc_idChuongKhoaHoc` INT NOT NULL,
  PRIMARY KEY (`idBaiHoc`), 
  INDEX `fk_BaiHoc_ChuongKhoaHoc1_idx` (`ChuongKhoaHoc_idChuongKhoaHoc`) VISIBLE, 
 CONSTRAINT `fk_BaiHoc_ChuongKhoaHoc1` FOREIGN KEY (`ChuongKhoaHoc_idChuongKhoaHoc`) 
 REFERENCES `cfb2fjadl5i6mh6w`.`ChuongKhoaHoc` (`idChuongKhoaHoc`) ON
DELETE CASCADE ON
UPDATE NO ACTION
	) ENGINE = INNODB;








-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`HocVien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`HocVien` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`HocVien` (
 `idHocVien` INT NOT NULL AUTO_INCREMENT,
 `TenHocVien` VARCHAR(256) NULL,
 `NgaySinh` DATETIME NULL,
 `Email` VARCHAR(256) NULL,
 `TaiKhoan_idTaiKhoan` INT NOT NULL, PRIMARY KEY (`idHocVien`), INDEX `fk_HocVien_TaiKhoan1_idx` (`TaiKhoan_idTaiKhoan` ASC) VISIBLE, CONSTRAINT `fk_HocVien_TaiKhoan` FOREIGN KEY (`TaiKhoan_idTaiKhoan`) REFERENCES `cfb2fjadl5i6mh6w`.`TaiKhoan` (`idTaiKhoan`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`HocVien_dahoc_Video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`HocVien_dahoc_Video` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`HocVien_dahoc_Video` (
 `HocVien_idHocVien` INT NOT NULL,
 `Video_idVideo` INT NOT NULL, PRIMARY KEY (`HocVien_idHocVien`, `Video_idVideo`), INDEX `fk_HocVien_has_Video_HocVien1_idx` (`HocVien_idHocVien` ASC) VISIBLE, CONSTRAINT `fk_HocVien_has_Video_HocVien1` FOREIGN KEY (`HocVien_idHocVien`) REFERENCES `cfb2fjadl5i6mh6w`.`HocVien` (`idHocVien`) ON
DELETE CASCADE ON
UPDATE NO ACTION, CONSTRAINT `fk_HocVien_has_Video_Video1` FOREIGN KEY (`Video_idVideo`) REFERENCES `cfb2fjadl5i6mh6w`.`Video` (`idVideo`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`HocVien_danhgia_KhoaHoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`HocVien_danhgia_KhoaHoc` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`HocVien_danhgia_KhoaHoc` (
 `HocVien_idHocVien` INT NOT NULL,
 `KhoaHoc_IdKhoaHoc` INT NOT NULL,
 `NhanXet` VARCHAR(2048) NULL,
 `Diem` INT NULL,
 `NgayDanhGia` DATETIME, PRIMARY KEY (`HocVien_idHocVien`, `KhoaHoc_IdKhoaHoc`), INDEX `fk_HocVien_has_KhoaHoc_KhoaHoc2_idx` (`KhoaHoc_IdKhoaHoc` ASC) VISIBLE, INDEX `fk_HocVien_has_KhoaHoc_HocVien2_idx` (`HocVien_idHocVien` ASC) VISIBLE, CONSTRAINT `fk_HocVien_has_KhoaHoc_HocVien2` FOREIGN KEY (`HocVien_idHocVien`) REFERENCES `cfb2fjadl5i6mh6w`.`HocVien` (`idHocVien`) ON
DELETE CASCADE ON
UPDATE NO ACTION, CONSTRAINT `fk_HocVien_has_KhoaHoc_KhoaHoc2` FOREIGN KEY (`KhoaHoc_IdKhoaHoc`) REFERENCES `cfb2fjadl5i6mh6w`.`KhoaHoc` (`IdKhoaHoc`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`HocVien_mua_KhoaHoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`HocVien_mua_KhoaHoc` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`HocVien_mua_KhoaHoc` (
 `KhoaHoc_IdKhoaHoc` INT NOT NULL,
 `HocVien_idHocVien` INT NOT NULL,
 `NgayDangKy` DATETIME NULL, PRIMARY KEY (`KhoaHoc_IdKhoaHoc`, `HocVien_idHocVien`), INDEX `fk_KhoaHoc_has_HocVien_HocVien1_idx` (`HocVien_idHocVien` ASC) VISIBLE, INDEX `fk_KhoaHoc_has_HocVien_KhoaHoc1_idx` (`KhoaHoc_IdKhoaHoc` ASC) VISIBLE, CONSTRAINT `fk_KhoaHoc_has_HocVien_KhoaHoc1` FOREIGN KEY (`KhoaHoc_IdKhoaHoc`) REFERENCES `cfb2fjadl5i6mh6w`.`KhoaHoc` (`IdKhoaHoc`) ON
DELETE CASCADE ON
UPDATE NO ACTION, CONSTRAINT `fk_KhoaHoc_has_HocVien_HocVien1` FOREIGN KEY (`HocVien_idHocVien`) REFERENCES `cfb2fjadl5i6mh6w`.`HocVien` (`idHocVien`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`HocVien_yeuthich_KhoaHoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`HocVien_yeuthich_KhoaHoc` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`HocVien_yeuthich_KhoaHoc` (
 `HocVien_idHocVien` INT NOT NULL,
 `KhoaHoc_IdKhoaHoc` INT NOT NULL, PRIMARY KEY (`HocVien_idHocVien`, `KhoaHoc_IdKhoaHoc`), INDEX `fk_HocVien_has_KhoaHoc_KhoaHoc1_idx` (`KhoaHoc_IdKhoaHoc` ASC) VISIBLE, INDEX `fk_HocVien_has_KhoaHoc_HocVien1_idx` (`HocVien_idHocVien` ASC) VISIBLE, CONSTRAINT `fk_HocVien_has_KhoaHoc_HocVien1` FOREIGN KEY (`HocVien_idHocVien`) REFERENCES `cfb2fjadl5i6mh6w`.`HocVien` (`idHocVien`) ON
DELETE CASCADE ON
UPDATE NO ACTION, CONSTRAINT `fk_HocVien_has_KhoaHoc_KhoaHoc1` FOREIGN KEY (`KhoaHoc_IdKhoaHoc`) REFERENCES `cfb2fjadl5i6mh6w`.`KhoaHoc` (`IdKhoaHoc`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;










-- MySQL Script generated by MySQL Workbench
-- Tue Dec 29 16:50:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cfb2fjadl5i6mh6w
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cfb2fjadl5i6mh6w` ;

-- -----------------------------------------------------
-- Schema cfb2fjadl5i6mh6w
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cfb2fjadl5i6mh6w` DEFAULT CHARACTER SET utf8 ; USE `cfb2fjadl5i6mh6w` ;

-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`BaiHoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`BaiHoc` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`BaiHoc` (
 `idBaiHoc` INT NOT NULL AUTO_INCREMENT,
 `TenBaiHoc` VARCHAR(256) NULL,
 `Mieu ta` VARCHAR(1028) NULL,
 `ChuongKhoaHoc_idChuongKhoaHoc` INT NOT NULL, PRIMARY KEY (`idBaiHoc`), INDEX `fk_BaiHoc_ChuongKhoaHoc1_idx` (`ChuongKhoaHoc_idChuongKhoaHoc` ASC) VISIBLE, CONSTRAINT `fk_BaiHoc_ChuongKhoaHoc1` FOREIGN KEY (`ChuongKhoaHoc_idChuongKhoaHoc`) REFERENCES `cfb2fjadl5i6mh6w`.`ChuongKhoaHoc` (`idChuongKhoaHoc`) ON
DELETE CASCADE ON
UPDATE CASCADE) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`ChuongKhoaHoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`ChuongKhoaHoc` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`ChuongKhoaHoc` (
 `idChuongKhoaHoc` INT NOT NULL AUTO_INCREMENT,
 `TenChuong` VARCHAR(100) NULL,
 `KhoaHoc_IdKhoaHoc` INT NOT NULL, PRIMARY KEY (`idChuongKhoaHoc`), INDEX `fk_ChuongKhoaHoc_KhoaHoc1_idx` (`KhoaHoc_IdKhoaHoc` ASC) VISIBLE, CONSTRAINT `fk_ChuongKhoaHoc_KhoaHoc1` FOREIGN KEY (`KhoaHoc_IdKhoaHoc`) REFERENCES `cfb2fjadl5i6mh6w`.`KhoaHoc` (`IdKhoaHoc`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`GiangVien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`GiangVien` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`GiangVien` (
 `idGiangVien` INT NOT NULL AUTO_INCREMENT,
 `TenGiangVien` VARCHAR(256) NULL,
 `NgaySinh` DATETIME NULL,
 `MoTa` VARCHAR(2048) NULL,
 `HinhDaiDien` VARCHAR(2048) NULL,
 `Email` VARCHAR(256) NULL,
 `TaiKhoan_idTaiKhoan` INT NOT NULL, PRIMARY KEY (`idGiangVien`), INDEX `fk_GiangVien_TaiKhoan1_idx` (`TaiKhoan_idTaiKhoan` ASC) VISIBLE, UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE, CONSTRAINT `fk_GiangVien_TaiKhoan` FOREIGN KEY (`TaiKhoan_idTaiKhoan`) REFERENCES `cfb2fjadl5i6mh6w`.`TaiKhoan` (`idTaiKhoan`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`HocVien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`HocVien` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`HocVien` (
 `idHocVien` INT NOT NULL AUTO_INCREMENT,
 `TenHocVien` VARCHAR(256) NULL,
 `NgaySinh` DATETIME NULL,
 `Email` VARCHAR(256) NULL,
 `TaiKhoan_idTaiKhoan` INT NOT NULL, PRIMARY KEY (`idHocVien`), INDEX `fk_HocVien_TaiKhoan1_idx` (`TaiKhoan_idTaiKhoan` ASC) VISIBLE, CONSTRAINT `fk_HocVien_TaiKhoan` FOREIGN KEY (`TaiKhoan_idTaiKhoan`) REFERENCES `cfb2fjadl5i6mh6w`.`TaiKhoan` (`idTaiKhoan`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`HocVien_dahoc_Video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`HocVien_dahoc_Video` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`HocVien_dahoc_Video` (
 `HocVien_idHocVien` INT NOT NULL,
 `Video_idVideo` INT NOT NULL, PRIMARY KEY (`HocVien_idHocVien`, `Video_idVideo`), INDEX `fk_HocVien_has_Video_HocVien1_idx` (`HocVien_idHocVien` ASC) VISIBLE, CONSTRAINT `fk_HocVien_has_Video_HocVien1` FOREIGN KEY (`HocVien_idHocVien`) REFERENCES `cfb2fjadl5i6mh6w`.`HocVien` (`idHocVien`) ON
DELETE CASCADE ON
UPDATE NO ACTION, CONSTRAINT `fk_HocVien_has_Video_Video1` FOREIGN KEY (`Video_idVideo`) REFERENCES `cfb2fjadl5i6mh6w`.`Video` (`idVideo`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`HocVien_danhgia_KhoaHoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`HocVien_danhgia_KhoaHoc` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`HocVien_danhgia_KhoaHoc` (
 `HocVien_idHocVien` INT NOT NULL,
 `KhoaHoc_IdKhoaHoc` INT NOT NULL,
 `NhanXet` VARCHAR(2048) NULL,
 `Diem` INT NULL,
 `NgayDanhGia` DATETIME, PRIMARY KEY (`HocVien_idHocVien`, `KhoaHoc_IdKhoaHoc`), INDEX `fk_HocVien_has_KhoaHoc_KhoaHoc2_idx` (`KhoaHoc_IdKhoaHoc` ASC) VISIBLE, INDEX `fk_HocVien_has_KhoaHoc_HocVien2_idx` (`HocVien_idHocVien` ASC) VISIBLE, CONSTRAINT `fk_HocVien_has_KhoaHoc_HocVien2` FOREIGN KEY (`HocVien_idHocVien`) REFERENCES `cfb2fjadl5i6mh6w`.`HocVien` (`idHocVien`) ON
DELETE CASCADE ON
UPDATE NO ACTION, CONSTRAINT `fk_HocVien_has_KhoaHoc_KhoaHoc2` FOREIGN KEY (`KhoaHoc_IdKhoaHoc`) REFERENCES `cfb2fjadl5i6mh6w`.`KhoaHoc` (`IdKhoaHoc`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`HocVien_mua_KhoaHoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`HocVien_mua_KhoaHoc` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`HocVien_mua_KhoaHoc` (
 `KhoaHoc_IdKhoaHoc` INT NOT NULL,
 `HocVien_idHocVien` INT NOT NULL,
 `NgayDangKy` DATETIME NULL, PRIMARY KEY (`KhoaHoc_IdKhoaHoc`, `HocVien_idHocVien`), INDEX `fk_KhoaHoc_has_HocVien_HocVien1_idx` (`HocVien_idHocVien` ASC) VISIBLE, INDEX `fk_KhoaHoc_has_HocVien_KhoaHoc1_idx` (`KhoaHoc_IdKhoaHoc` ASC) VISIBLE, CONSTRAINT `fk_KhoaHoc_has_HocVien_KhoaHoc1` FOREIGN KEY (`KhoaHoc_IdKhoaHoc`) REFERENCES `cfb2fjadl5i6mh6w`.`KhoaHoc` (`IdKhoaHoc`) ON
DELETE CASCADE ON
UPDATE NO ACTION, CONSTRAINT `fk_KhoaHoc_has_HocVien_HocVien1` FOREIGN KEY (`HocVien_idHocVien`) REFERENCES `cfb2fjadl5i6mh6w`.`HocVien` (`idHocVien`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`HocVien_yeuthich_KhoaHoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`HocVien_yeuthich_KhoaHoc` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`HocVien_yeuthich_KhoaHoc` (
 `HocVien_idHocVien` INT NOT NULL,
 `KhoaHoc_IdKhoaHoc` INT NOT NULL, PRIMARY KEY (`HocVien_idHocVien`, `KhoaHoc_IdKhoaHoc`), INDEX `fk_HocVien_has_KhoaHoc_KhoaHoc1_idx` (`KhoaHoc_IdKhoaHoc` ASC) VISIBLE, INDEX `fk_HocVien_has_KhoaHoc_HocVien1_idx` (`HocVien_idHocVien` ASC) VISIBLE, CONSTRAINT `fk_HocVien_has_KhoaHoc_HocVien1` FOREIGN KEY (`HocVien_idHocVien`) REFERENCES `cfb2fjadl5i6mh6w`.`HocVien` (`idHocVien`) ON
DELETE CASCADE ON
UPDATE NO ACTION, CONSTRAINT `fk_HocVien_has_KhoaHoc_KhoaHoc1` FOREIGN KEY (`KhoaHoc_IdKhoaHoc`) REFERENCES `cfb2fjadl5i6mh6w`.`KhoaHoc` (`IdKhoaHoc`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`KhoaHoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`KhoaHoc` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`KhoaHoc` (
 `IdKhoaHoc` INT NOT NULL AUTO_INCREMENT,
 `MaKhoaHoc` CHAR(20) NULL,
 `TenKhoaHoc` VARCHAR(256) NULL,
 `MoTaNgan` VARCHAR(2048) NULL,
 `MoTaChiTiet` VARCHAR(4096) NULL,
 `DiemDanhGia` FLOAT NULL,
 `SoLuongHVDanhGia` INT NULL,
 `SoLuongHVDangKy` INT NULL,
 `NgayCapNhat` DATETIME NULL,
 `SoLuotXem` INT NULL,
 `HocPhi` FLOAT NULL,
 `KhuyenMai` FLOAT NULL,
 `HinhDaiDien` VARCHAR(2048) NULL,
 `TrangThai` TINYINT NULL,
 `NguoiTao` INT NOT NULL,
 `NguoiDay` INT NOT NULL,
 `LinhVuc` INT NOT NULL,
 `HienThi` INT NOT NULL DEFAULT 1, PRIMARY KEY (`IdKhoaHoc`), INDEX `fk_KhoaHoc_GiangVien1_idx` (`NguoiTao` ASC) VISIBLE, INDEX `fk_KhoaHoc_GiangVien1_idx1` (`NguoiDay` ASC) VISIBLE, INDEX `fk_KhoaHoc_LinhVucCap21_idx` (`LinhVuc` ASC) VISIBLE, CONSTRAINT `fk_KhoaHoc_GiangVien` FOREIGN KEY (`NguoiTao`) REFERENCES `cfb2fjadl5i6mh6w`.`GiangVien` (`idGiangVien`) ON
DELETE CASCADE ON
UPDATE NO ACTION, CONSTRAINT `fk_KhoaHoc_GiangVien1` FOREIGN KEY (`NguoiDay`) REFERENCES `cfb2fjadl5i6mh6w`.`GiangVien` (`idGiangVien`) ON
DELETE CASCADE ON
UPDATE NO ACTION, CONSTRAINT `fk_KhoaHoc_LinhVucCap21` FOREIGN KEY (`LinhVuc`) REFERENCES `cfb2fjadl5i6mh6w`.`LinhVucCap2` (`idLinhVucCap2`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`LinhVucCap1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`LinhVucCap1` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`LinhVucCap1` (
 `idLinhVuc` INT NOT NULL AUTO_INCREMENT,
 `MaLinhVuc` CHAR(20) NULL,
 `TenLinhVuc` VARCHAR(256) NULL, PRIMARY KEY (`idLinhVuc`)) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`LinhVucCap2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`LinhVucCap2` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`LinhVucCap2` (
 `idLinhVucCap2` INT NOT NULL AUTO_INCREMENT,
 `MaLinhVuc` CHAR(20) NULL,
 `TenLinhVuc` VARCHAR(256) NULL,
 `LinhVucCap1_idLinhVuc` INT NOT NULL, PRIMARY KEY (`idLinhVucCap2`), INDEX `fk_LinhVucCap2_LinhVucCap11_idx` (`LinhVucCap1_idLinhVuc` ASC) VISIBLE, CONSTRAINT `fk_LinhVucCap2_LinhVucCap11` FOREIGN KEY (`LinhVucCap1_idLinhVuc`) REFERENCES `cfb2fjadl5i6mh6w`.`LinhVucCap1` (`idLinhVuc`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`LoaiTaiKhoan` ;

-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`LoaiTaiKhoan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`LoaiTaiKhoan` (
 `idLoaiTaiKhoan` INT NOT NULL,
 `TenLoaiTaiKhoan` VARCHAR(256), PRIMARY KEY (`idLoaiTaiKhoan`)
);
-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`TaiKhoan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`TaiKhoan` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`TaiKhoan` (
 `idTaiKhoan` INT NOT NULL AUTO_INCREMENT,
 `TenTaiKhoan` VARCHAR(256) NULL,
 `MatKhau` BINARY(60) NULL,
 `Salt` BINARY(16) NULL,
 `LoaiTaiKhoan` INT NULL,
 `TrangThai` INT NULL, PRIMARY KEY (`idTaiKhoan`), UNIQUE INDEX `TenTaiKhoan_UNIQUE` (`TenTaiKhoan` ASC) VISIBLE, CONSTRAINT `fk_TaiKhoan_LoaiTaiKhoan1` FOREIGN KEY (`LoaiTaiKhoan`) REFERENCES `cfb2fjadl5i6mh6w`.`LoaiTaiKhoan` (`idLoaiTaiKhoan`) ON
DELETE CASCADE ON
UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfb2fjadl5i6mh6w`.`Video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfb2fjadl5i6mh6w`.`Video` ;
CREATE TABLE IF NOT EXISTS `cfb2fjadl5i6mh6w`.`Video` (
 `idVideo` INT NOT NULL AUTO_INCREMENT,
 `TenVideo` VARCHAR(256) NULL,
 `DiaChi` VARCHAR(1028) NULL,
 `BaiHoc_idBaiHoc` INT NOT NULL, PRIMARY KEY (`idVideo`), INDEX `fk_Video_BaiHoc1_idx` (`BaiHoc_idBaiHoc` ASC) VISIBLE, CONSTRAINT `fk_Video_BaiHoc1` FOREIGN KEY (`BaiHoc_idBaiHoc`) REFERENCES `cfb2fjadl5i6mh6w`.`BaiHoc` (`idBaiHoc`) ON
DELETE CASCADE ON
UPDATE NO ACTION) ENGINE = InnoDB;